import type { Metadata } from "next";
import {Roboto } from '@next/font/google'
import '@styles/layout.scss'
import Nav from "./nav";
import '@styles/reset.css'

export const metadata: Metadata = {
  title: "Create Your Mom",
  description: "Generated by create next app",
};

export const viewport = {
  name: "viewport",
  content: "width=device-width, initial-scale=1.0"
};

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={roboto.className}>
          <div className="page_layout">
            <div className="nav">
              <Nav />
            </div>

            <main>
              <header>Im a header</header>

              <section>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente reprehenderit nam amet repellat harum laudantium quibusdam sit aut dolore architecto necessitatibus assumenda deleniti molestias cupiditate cum nesciunt blanditiis, in accusamus?
                Obcaecati quibusdam magni laboriosam ad maiores harum at laudantium, perspiciatis nobis non ipsum illo odit temporibus, dignissimos sint ut, nostrum facere sed libero quod eveniet adipisci natus cumque. Nam, sint.
                Alias nisi exercitationem ullam, perferendis laudantium repudiandae atque quibusdam. Optio sint ad, sapiente saepe fugiat porro iusto delectus nobis, eveniet doloremque deserunt. Perspiciatis facilis, dolorem repellendus doloremque sapiente pariatur quibusdam.
                Sit quam sunt neque animi rem iste reprehenderit minus labore, dicta ab assumenda deserunt, culpa odio provident quos sint dolore? Officiis adipisci, libero quae fugiat hic dolorum atque ea veniam!
                Placeat molestias inventore doloremque deleniti sed nisi reprehenderit illum, fugiat iure at velit aliquid asperiores consequatur itaque quos voluptate, maiores perferendis iusto aperiam nobis sit dolorem aliquam facere enim? Officiis!
                Sunt vero laudantium eaque reiciendis earum iusto placeat inventore ipsam voluptas? Praesentium, pariatur. Laudantium, quibusdam molestiae eaque animi officia ipsa corrupti ea dolor aspernatur deleniti reprehenderit at et fugit mollitia.
                Molestiae exercitationem in magnam voluptates, ab minima saepe nihil assumenda eos eligendi accusantium illum minus maiores nisi fugit culpa, sapiente aliquam iste vitae! Maxime mollitia soluta amet, vero autem numquam!
                Voluptatum voluptas itaque minus officiis earum, architecto assumenda qui quo aperiam quibusdam perferendis vero magni cumque consectetur maiores veniam laudantium suscipit, ipsam saepe exercitationem at? Molestiae nobis recusandae minus corrupti.
                Ad laboriosam molestiae laborum! Amet, odit labore. Ratione, consequuntur temporibus eligendi nam aspernatur quia laudantium, quos commodi, maxime saepe rerum hic expedita porro. Non, placeat! Harum alias ea iste reiciendis.
                Odio modi eius animi corrupti impedit quidem mollitia maxime excepturi accusamus magni optio facilis hic, neque explicabo minima unde consequatur iure ipsum, aperiam suscipit ratione sequi. Doloremque eveniet deleniti similique.
                Aperiam odit autem at quas harum veritatis id ducimus optio maiores dolorem fuga architecto libero adipisci, aliquam eveniet. Eos natus iure unde! Earum expedita ratione quasi alias perferendis nesciunt reiciendis.
                Aperiam quisquam quos natus illum corporis nisi culpa dolores, doloremque in optio eligendi ad commodi laborum minima! Inventore beatae excepturi, nulla fugiat perspiciatis tenetur corrupti soluta earum, cum recusandae eum.
                Rerum ducimus aspernatur soluta necessitatibus velit autem eaque assumenda, delectus quae provident aut tenetur nam neque commodi repellendus ab suscipit doloremque nulla quas saepe non doloribus aperiam veritatis facilis. Optio.
                Dolores molestias fuga alias! Eos reiciendis commodi, maiores qui iusto culpa magnam laudantium iste omnis facere? Aliquid qui dolor non beatae voluptatem veniam. Numquam, eius soluta ex culpa consequatur velit!
                Excepturi soluta suscipit quam vitae omnis fugiat possimus autem sed incidunt ut praesentium, ea explicabo eius! Corrupti non ipsa dolor debitis magni autem animi quo, a saepe molestias mollitia odio?
                Laboriosam ad culpa recusandae dignissimos, cupiditate maxime numquam cumque tenetur nam quae, dolores modi labore? Debitis nihil odit, recusandae officiis porro sint repellat, velit sed veniam eius dicta commodi mollitia!
                Amet maxime rerum odit beatae et perferendis saepe in sapiente asperiores vitae recusandae fuga, voluptatibus dolore consequatur maiores fugit assumenda laudantium cum accusamus, quos hic facere? Rerum officia vero voluptatem!
                Earum optio eveniet maxime porro nesciunt? Aliquam odio doloremque in possimus, perferendis amet est et optio dignissimos maiores eaque. Numquam quo esse iusto dolor consectetur cupiditate quibusdam mollitia ipsum unde!
                Velit, quis ab recusandae, repellendus earum deserunt est, rem dolorum provident ut cumque enim soluta iusto dolores perspiciatis. Delectus dicta voluptas incidunt. Architecto facilis eius eum! Hic dolor aliquam vero.
                Maxime tenetur, debitis quos inventore eveniet veniam ullam sed, maiores accusantium explicabo odit dicta unde beatae repellat. Hic, magni. Molestias ab repellendus praesentium quibusdam? Cum optio fuga assumenda tenetur ea?
                Laborum delectus soluta mollitia voluptate id at officia nesciunt repudiandae saepe deserunt porro quo corrupti, impedit illo necessitatibus aut ex, laboriosam, voluptates enim quas assumenda sequi! Porro consequuntur quas ullam?
                Numquam minima ea fugit at sapiente soluta repellat vero officiis dolores! Neque vel in quo quae at earum voluptatum. Explicabo quae tenetur modi rerum distinctio natus non fugiat sapiente quam.
                Corporis obcaecati alias exercitationem nisi veritatis consequatur libero, excepturi animi. Quas est consequuntur consectetur. Voluptas dicta suscipit asperiores quo inventore iste doloribus, corrupti repudiandae sit blanditiis pariatur impedit, voluptate sapiente!
                Ad commodi, optio laudantium ipsum inventore fugiat voluptatem neque officia officiis! Ex facere aspernatur ut tenetur libero, tempora deleniti doloribus reiciendis in quibusdam nesciunt. Amet accusamus nobis vel veniam consectetur?
                Veniam odio ipsum aperiam repudiandae doloremque eveniet consequuntur perspiciatis. Ab dolorum accusantium ratione iusto quidem vero ullam hic, cumque omnis! Eaque rem qui nam minus quia accusantium quas quasi totam?
                Distinctio provident velit ipsum, totam aperiam, vero veniam debitis corporis maiores aliquam optio blanditiis facere cumque asperiores perferendis voluptates repellendus iure doloribus ex quaerat? Molestias iure veritatis magni blanditiis non!
                Accusamus omnis facilis obcaecati similique dolorum nulla iusto ea dolores nemo est, voluptatibus, corporis sunt consequuntur vitae. Placeat deserunt adipisci ipsam nemo! Quisquam officia deserunt, dolorum vel error earum ipsum?
                Possimus culpa vel totam, error pariatur dolorem, velit, quaerat impedit iusto dicta atque dignissimos. Distinctio repellendus consequatur dolores unde fugiat, voluptatibus similique cum natus hic dicta commodi excepturi atque ipsum.
                Harum, consectetur expedita deserunt soluta officiis esse quos dignissimos velit voluptatum odio ducimus nulla fuga, sed, eius non possimus rem cupiditate eligendi laborum libero a error autem ipsam? Necessitatibus, earum?
                Autem nemo, optio deleniti nulla tenetur maxime magnam blanditiis expedita, inventore voluptas, saepe ducimus facilis quod recusandae? Voluptas asperiores, facere at itaque autem aliquid rerum impedit magnam natus nemo qui!
                Exercitationem sint natus, explicabo quisquam atque laborum recusandae ratione doloribus laboriosam fugit tempore? Nulla magnam eligendi, tempora tenetur dignissimos itaque sint perspiciatis quibusdam nam veniam voluptate omnis illum, magni dolores?
                Facilis nobis, possimus eius aperiam corporis hic nihil ad placeat ipsa odio sequi similique fugit ipsum! Dolorum, distinctio quisquam eveniet cumque et labore temporibus sit voluptatem repudiandae, harum hic perspiciatis.
                Explicabo inventore nihil officiis facere quo quibusdam non natus voluptatum animi eligendi. Ad sit porro architecto! Minus quibusdam delectus qui recusandae dolore. Aliquam nemo fuga a sint debitis! Voluptatum, perspiciatis?
                Tempora nihil, voluptas minus error vitae blanditiis sunt amet pariatur dolore similique tempore aut fugit nobis, dolor illo aliquam expedita officiis explicabo sit, labore temporibus cupiditate id assumenda. Hic, corrupti!
                Nihil delectus unde minus sequi laboriosam repellat iusto facilis saepe nulla. Nam est cum consequuntur consectetur rerum repellat saepe. Quae neque quidem facilis aspernatur nemo tempore cum amet saepe minima.
                Similique molestias dolor provident voluptate animi aliquid, aspernatur illo laudantium repellendus corrupti accusamus dolore officiis corporis exercitationem nulla suscipit, omnis neque sint cum deleniti magnam temporibus possimus earum laborum! Quas!
                Molestias ipsum et sequi recusandae iusto neque asperiores cumque, alias consectetur provident enim sunt, quasi amet a reprehenderit nobis? Libero laboriosam ab eos cupiditate recusandae inventore. Architecto odit fugiat illum!
                Laboriosam, vel? Hic ipsum dolor ipsam repellendus sint veniam sed repudiandae repellat dolorem minima aliquid illo molestiae tempora, id perferendis ipsa adipisci! Voluptate, recusandae ratione hic repudiandae placeat ipsa tempora!
                Maxime harum libero excepturi eius veritatis eligendi temporibus labore, molestias iusto. Recusandae nemo at sequi totam, unde adipisci voluptatibus quis aperiam nesciunt suscipit quidem, minus molestiae vero magnam veritatis qui!
                Doloribus minus commodi ipsa magni laudantium veniam dolorem hic facilis quasi aperiam autem vitae, obcaecati sapiente voluptates fugit nostrum eum nemo, impedit cumque ex? Est quis rem debitis dolores asperiores!
                Error, tenetur voluptas amet debitis architecto, a nam, saepe fugit aut vero sit veritatis magnam voluptates asperiores aliquid obcaecati! Voluptas ducimus eos doloribus porro quis qui laboriosam impedit id similique.
                Beatae placeat, blanditiis fugiat eum illo facere? Totam veritatis quidem ab cupiditate ad debitis id sapiente perferendis architecto placeat. Provident officia quidem aspernatur hic placeat quasi maiores molestias praesentium ratione.
                Dignissimos omnis tenetur autem odit reiciendis distinctio voluptate vero itaque illo alias modi nemo unde ad amet obcaecati repudiandae voluptatibus accusamus, quas ut maxime soluta quod? Omnis ab placeat autem.
                Fugit doloribus minus voluptatibus omnis dignissimos reiciendis sequi, laudantium fuga? Nesciunt et cum consectetur veniam. Aliquam, iure facilis. Deserunt ut reprehenderit, ex earum accusamus voluptate assumenda itaque vel exercitationem nesciunt.
                Aut architecto quidem velit repudiandae voluptates repellat placeat debitis nemo, dicta quod veritatis deleniti expedita earum quasi ad commodi perspiciatis dolorem voluptatibus aliquid eius quia ipsam, fugit quae? Nemo, dolore!
                Quidem enim nostrum dolores aliquam excepturi provident corrupti accusamus labore tempore error rem ipsam ipsa saepe modi recusandae consequuntur facere, sit veritatis veniam voluptate mollitia repudiandae fuga, tenetur dolorem. Totam!
                Aliquam animi expedita veniam atque asperiores obcaecati, at quaerat repellat accusantium. Eligendi velit iusto atque, error cum porro accusantium repellendus, ipsam quidem dignissimos culpa assumenda, enim eos quae? Quibusdam, ex?
                Ea beatae impedit veniam, in quibusdam facere eos libero nihil omnis quos iusto eligendi dicta repudiandae. Dolorem veniam, consectetur tenetur quibusdam quod eaque soluta suscipit tempora nihil placeat aspernatur maxime.
                Fugiat, aliquam! Dolorum inventore natus tempore nulla nobis necessitatibus cum, id ab in voluptatem facilis eaque aspernatur, eos consequuntur asperiores laborum esse? Quas et recusandae quia, velit enim veritatis excepturi?
                Ut, dignissimos incidunt laudantium nihil possimus, provident iusto ad quibusdam exercitationem magni corrupti consequatur quis voluptate praesentium a veniam sunt qui, veritatis eos quaerat vero consequuntur numquam. Ullam, quibusdam porro.
                Porro dolores voluptates consectetur deleniti, nesciunt, consequatur harum debitis dolore dignissimos provident beatae labore culpa vitae! Doloremque dolorem modi quaerat delectus possimus tempore cupiditate tempora fuga quae cum! Praesentium, officiis.
                Ab, perspiciatis aliquid iusto quibusdam corrupti similique reprehenderit impedit iure facilis labore! Itaque suscipit necessitatibus ad eum, autem unde minima exercitationem nihil est voluptatum non tempore ut provident blanditiis nisi?
                Sapiente quasi doloribus unde iste tempora facere debitis excepturi incidunt perspiciatis magnam molestias, illo vero quisquam omnis veritatis ratione aperiam architecto voluptatem, natus, quam est dignissimos aliquid? Sunt, assumenda dolores?
                Tenetur inventore sit accusamus tempore placeat dolore, quaerat odit autem error quas. Reprehenderit esse cum aspernatur explicabo harum tenetur nisi ea nobis praesentium, ex deleniti, eveniet suscipit sapiente odio nesciunt?
                Provident quis autem cumque enim omnis inventore maxime impedit temporibus? Inventore sequi quis cupiditate dolorem, consequatur itaque tempore distinctio cum provident beatae! Optio dignissimos architecto expedita consequuntur, sunt dolore suscipit?
                Nostrum voluptate impedit commodi, unde ipsam nisi ducimus temporibus officiis, labore corrupti tempora quidem? Voluptas iure, nostrum veniam est, molestias fugiat quibusdam cumque doloribus magni praesentium libero rem id alias!
                Minus beatae iure ex. Et aspernatur, alias possimus harum facilis blanditiis quae nostrum nam officiis ipsum nobis in optio aliquam similique accusamus libero quod laboriosam id exercitationem deleniti vero excepturi?
                Enim magni necessitatibus voluptatibus voluptas, placeat, dolorem delectus sapiente tempora illum nostrum quidem! Quidem, incidunt cupiditate. Quasi, beatae. Eaque, voluptatum aspernatur aperiam libero nemo cumque earum dignissimos. Vitae, voluptates dolorum.
                Laborum neque beatae corporis voluptatem. Quod incidunt ad vel quae reiciendis iusto obcaecati, fuga similique velit error, illum dicta officiis voluptatem maxime dolorum corrupti veritatis temporibus voluptas aperiam? Vero, repudiandae.
                Minus maxime obcaecati non dicta odio, facilis, laboriosam dolorem eveniet reiciendis reprehenderit excepturi repellat quaerat id, error rerum mollitia saepe expedita in cupiditate aut voluptate cumque. Quam harum vel quia.
                Quaerat asperiores ut culpa sint unde alias mollitia similique ad, molestiae inventore natus reiciendis enim temporibus blanditiis eligendi dolore corrupti, voluptates veritatis eaque molestias commodi iusto repellat! Veritatis, ipsa perspiciatis!
                Placeat eius tempore aut aperiam ad aspernatur doloremque repellendus soluta iusto voluptatem nemo similique consequuntur, minus veritatis eaque excepturi. Dolorum quasi in quas eaque expedita deserunt magnam a sint aperiam.
                Distinctio eum animi ab labore voluptatem dicta iste, architecto repellendus nobis ea repudiandae optio quia quisquam quo doloremque magni dolorem incidunt laudantium nulla ad, quaerat ullam dolor. Excepturi, enim beatae?
                Aspernatur veniam doloremque eius. Labore ex obcaecati officiis asperiores laborum dolore non, enim voluptate dolor nisi deserunt quae porro fugit quisquam rerum veniam! Error laudantium suscipit nisi beatae est perferendis.
                Reiciendis veritatis totam consequatur, doloremque perspiciatis corporis quos quidem soluta esse? Rerum quasi dolorem eum atque quam minus dicta. Omnis possimus incidunt corporis quod impedit, praesentium aperiam quidem pariatur minima.
                Quas velit quia pariatur aspernatur saepe unde autem aut perspiciatis quos consequatur assumenda quasi neque sed optio mollitia aliquam, vero quis quibusdam repellendus asperiores cumque! Excepturi eum ea nostrum saepe.
                Repellendus sequi quis tempore, consectetur aliquam culpa architecto recusandae dolorum cumque molestias eius dignissimos voluptas, asperiores, temporibus similique libero. Possimus asperiores voluptate quia voluptatem officiis cupiditate enim quasi, quis ad.
                Expedita beatae, quia enim labore maxime nulla magni officiis tempora excepturi, atque sequi molestias rerum natus temporibus voluptatibus libero, asperiores dolorem distinctio. Praesentium aliquam, eos quisquam quos nesciunt enim adipisci.
                A amet reiciendis vero modi, accusantium quam eaque nam quibusdam sapiente eligendi consequuntur saepe, atque doloribus minus cupiditate? Iste neque quis vel nam sunt praesentium, quibusdam numquam totam optio rerum.
                Delectus eius officia vel iste autem veniam non incidunt exercitationem enim? Odit accusantium molestiae quidem natus beatae delectus enim cumque tempore, repellat, cum reprehenderit dignissimos quam magni fuga porro corrupti!
                Dolorum quibusdam repellendus nihil aut accusantium nemo, officiis pariatur culpa voluptatem, voluptatum suscipit, labore nostrum atque itaque hic necessitatibus mollitia perspiciatis blanditiis non corrupti odit debitis! Cupiditate minus ab aspernatur!
                Voluptatum ad enim dolor cumque aut voluptatem eaque ipsam dolorem repellendus quas ducimus inventore earum sit numquam, esse quae! Hic, perspiciatis ipsum est veniam quas dolorem quibusdam deleniti assumenda odio?
                Totam architecto quibusdam optio hic molestias. Tenetur optio natus commodi pariatur delectus, numquam, mollitia recusandae suscipit perferendis sit accusantium saepe, nostrum nemo atque praesentium doloremque illum excepturi maxime! Obcaecati, deserunt.
                Maiores atque eligendi, molestias, odio commodi, quidem dolorem impedit quasi ducimus neque repellendus necessitatibus. Eos earum ut dolorem quisquam doloribus illo officia animi debitis id nesciunt, provident, neque quis voluptatibus.
                Laboriosam minus dolorum alias qui id excepturi nam culpa ea praesentium, aperiam cumque eveniet nemo voluptates porro corporis quia temporibus dolor! Voluptatibus totam debitis, provident facere laboriosam laudantium impedit inventore.
                Ipsa optio voluptas blanditiis, reiciendis aperiam nostrum obcaecati debitis. Quaerat illo sed nihil sint ducimus optio nobis sit, ipsum facere delectus reiciendis et doloremque ipsam deleniti minima omnis aliquam aperiam.
                Autem, laboriosam! Repudiandae placeat, eveniet aliquam necessitatibus iure temporibus commodi nobis fuga, ad sequi sed obcaecati corporis deleniti animi, asperiores labore cumque autem aliquid rerum. Velit modi fugiat dignissimos vero.
                Odio aspernatur libero in asperiores minus! Similique, voluptas eos ad id voluptatem non, esse perspiciatis consectetur optio libero quia aliquid ratione quas blanditiis odit, ex omnis sint minus vel? Sint?
                Commodi eum praesentium ducimus, dolore voluptate soluta, sequi doloribus minima eos tempore, harum eveniet ex ut reprehenderit animi! Vero ad error odit aut fugit, quam magnam quos voluptates culpa necessitatibus.
                Ducimus obcaecati, natus perferendis odio eum mollitia laboriosam laudantium iusto veniam libero, eligendi nemo esse, excepturi error commodi. Facilis iusto provident eos libero esse id labore impedit possimus facere ad?
                Laboriosam eos ut officiis laudantium rem dolor reprehenderit dolorum blanditiis fugit ipsum possimus sunt commodi optio id quae quis nam voluptates, libero odio similique maxime perferendis explicabo veniam eaque? Labore.
                Laborum id maxime qui eveniet earum repudiandae rem praesentium, nesciunt dignissimos delectus ratione, soluta molestiae corporis porro at quia libero cupiditate minima eos quas necessitatibus accusantium sunt. Natus, architecto dolores.
                Est dolorem recusandae, officiis optio libero eligendi repellendus officia quod consectetur omnis expedita soluta explicabo molestias ullam sint tenetur consequuntur debitis quis inventore fugit repellat nihil sit velit magnam? Fugit.
                Minus aliquam natus nihil hic in tenetur commodi quisquam eius accusamus eum. Illum incidunt, vel cumque odit nam eligendi similique explicabo. Exercitationem consequuntur dolore eveniet ipsum quod nisi, maxime nam?
                Impedit mollitia velit perspiciatis ipsum voluptas at doloribus eaque obcaecati magni exercitationem voluptates quidem modi, excepturi, sit delectus commodi beatae veniam fugiat. Minus tempore, veniam molestias labore quo voluptas hic.
                Quaerat, cum porro odio commodi minus repellat distinctio necessitatibus dolore saepe itaque odit omnis! Praesentium consequatur iusto voluptatibus ullam ipsam et culpa iure quaerat, sapiente id magnam voluptates ab assumenda.
                Accusantium repudiandae quaerat repellendus labore, fugit dolores eveniet optio quod quo vero maxime, nihil corrupti? Itaque voluptates ullam blanditiis quidem! Architecto rem nisi odit nostrum eligendi. Ratione voluptatibus id similique.
                Deleniti praesentium nemo illo quod in vel velit voluptatibus earum cupiditate quo voluptate et, asperiores eos consectetur perspiciatis expedita? Id vitae accusantium esse! Obcaecati voluptates voluptatum unde harum libero eveniet?
                Dolor quo eum animi fuga corporis autem magnam numquam alias eos, possimus debitis harum expedita sed, cupiditate tempore eveniet tempora rerum quas consequatur voluptas. Optio provident eveniet voluptatem alias voluptas!
                Corrupti reiciendis blanditiis amet. Maiores commodi facere, voluptatibus exercitationem asperiores repudiandae illum modi laboriosam maxime magni obcaecati earum et iure ut, quasi quisquam, soluta accusantium consectetur ducimus impedit excepturi ipsa.
                Doloribus atque expedita perferendis, dolore aperiam nulla neque, aspernatur voluptatum, nam consequuntur accusamus quam sapiente veniam! Repellat est aliquam nemo vel sequi unde adipisci minima ad placeat, illo laboriosam saepe.
                Ratione praesentium nisi in asperiores pariatur doloribus aliquid suscipit animi sint veniam, molestias iste voluptatibus amet commodi cum laboriosam debitis sequi voluptatem temporibus error ullam? Consequuntur cumque consequatur recusandae ad!
                Ipsum quos voluptates expedita ullam dignissimos, sed vero atque amet cum praesentium recusandae voluptatum, quasi, facilis optio mollitia fugiat eos autem labore dolores! Consequatur rem suscipit a cupiditate recusandae non!
                Hic, eum, sed quibusdam sit, minus distinctio velit suscipit nostrum totam sint iste earum fugit culpa. Nisi error, quas reprehenderit natus excepturi iste, inventore nesciunt fugit sapiente quibusdam amet nemo.
                Labore repudiandae illo facere eius fuga eligendi dolorem commodi, vitae at impedit? Quibusdam blanditiis perspiciatis facilis ratione! Reprehenderit explicabo consectetur minus, maxime sunt enim, quam aliquid obcaecati repellat nobis ut.
                Consectetur, cumque. Ullam nihil reiciendis dolorum officiis voluptate corrupti earum, nam nostrum veniam cum libero? Accusantium exercitationem saepe asperiores aperiam. Accusantium placeat fugiat sint dolorum possimus vero quaerat error nulla!
                Ipsam pariatur totam nihil saepe adipisci! Molestiae soluta nemo eveniet repudiandae cumque amet, perferendis nihil nesciunt expedita quibusdam earum incidunt non nostrum unde natus consectetur, illo vero temporibus molestias in.
                Minima maxime dicta, cupiditate ut ullam distinctio magnam sit? Corrupti sint assumenda culpa cumque vel repellendus ullam adipisci ea rem iusto voluptate, at beatae saepe hic consequatur facere! Temporibus, vel.
                Perferendis doloribus cupiditate nobis similique expedita aspernatur veritatis debitis tempora incidunt repellat autem pariatur temporibus laudantium laborum blanditiis at, sint aliquid totam alias itaque sapiente delectus, numquam facilis voluptatibus! Laboriosam!
                Magni, culpa, placeat sed enim, voluptate ipsa excepturi harum dolorem similique quaerat optio alias repudiandae beatae autem voluptates numquam minus nesciunt explicabo consequuntur ab! Nostrum nisi culpa aspernatur perspiciatis et.
              </section>

              <footer>
                Im a footer
              </footer>
            </main>
          </div>
      </body>
    </html>
  );
}
